steps:
  #build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-flask-app-$_NAMESPACE', '.']
  #push container image
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/simple-flask-app-$_NAMESPACE']
  #deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke-$_NAMESPACE.yaml
  - --image=gcr.io/$PROJECT_ID/simple-flask-app-$_NAMESPACE
  - --location=us-central1-a
  - --cluster=master-cluster
  - --namespace=flask-app-$_NAMESPACE


options:
  logging: CLOUD_LOGGING_ONLY